# Generated by Django 2.0.7 on 2018-07-12 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SEOMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.CharField(max_length=50, verbose_name='Nazwa strony')),
                ('title', models.CharField(max_length=120, verbose_name='Meta tytuł')),
                ('meta_description', models.CharField(max_length=170, verbose_name='Meta Opis')),
                ('keywords', models.TextField(verbose_name='Słowa kluczowe')),
            ],
            options={
                'verbose_name': 'Ustawienia Meta',
                'verbose_name_plural': 'Ustawienia Meta',
            },
        ),
    ]
